project/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, Response, send_file
from werkzeug.security import generate_password_hash, check_password_hash
from project.forms import RegistrationForm
from project.models import db, User

from flask_login import login_required, login_user, logout_user
auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        # login code goes here
        email = request.form.get('email')
        password = request.form.get('password')
        remember = True if request.form.get('remember') else False

        user = User.query.filter_by(email=email).first()

        # check if the user actually exists
        # take the user-supplied password, hash it, and compare it to the hashed password in the database
        if not user:
            print("User not found")
            flash('The email address does not exist, please try again')
            return redirect(url_for('auth.login'))  # if the user doesn't exist or password is wrong, reload the page

        if not user or not check_password_hash(user.password, password):
            print("Invalid password")
            flash('Please check your password and try again.')
            return redirect(url_for('auth.login'))  # if the user doesn't exist or password is wrong, reload the page

        # if the above check passes, then we know the user has the right credentials
        login_user(user, remember=remember)
        return redirect(url_for('swimmer.profile'))

    return render_template('login.html')


@auth.route('/register', methods=["GET", "POST"])
def register():
    form = RegistrationForm(request.form)
    if request.method == "POST" and form.validate():
        print('validated')
        # code to validate and add user to database goes here
        email = form.email.data
        name = form.name.data
        password = form.password.data
        height = form.height.data
        weight = form.weight.data
        gender = form.gender.data
        dob = form.dob.data

        user = User.query.filter_by(
            email=email).first()  # if this returns a user, then the email already exists in database

        if user:  # if a user is found, we want to redirect back to signup page so user can try again
            flash('Email address already exists')
            return redirect(url_for('register'))

        # create a new user with the form data. Hash the password so the plaintext version isn't saved.
        new_user = User(email=email, name=name, password=generate_password_hash(password, method='pbkdf2:sha256'),
                        height=height, weight=weight, gender=gender, date_of_birth=dob)

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for('login'))

    return render_template('register.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

project/main.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/about')
def about():
    return render_template('about.html')

project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">

    <!-- site metas -->
    <title>{% block title %}Swimming Detection{% endblock %}</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- App icon -->
    <link rel="icon" href="https://upload.wikimedia.org/wikipedia/th/thumb/5/51/Logo_ku_th.svg/1200px-Logo_ku_th.svg.png">


    <!-- bootstrap css -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.css') }}">
    <!-- style css -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/style.css') }}">
    <!-- responsive-->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/responsive.css') }}">
    <!-- awesome font family -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />#}

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->

    <!-- Javascript files-->
    <script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/jquery-3.0.0.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/custom.js') }}"></script>

</head>
<!-- body -->
<body class="main-layout {% block page_class %}{% endblock %}">
<!-- loader  -->
{#<div class="loader_bg">#}
{#    <div class="loader"><img src="{{ url_for('static',filename='img/loading.gif') }}" alt=""/></div>#}
{#</div>#}
<!-- end loader -->
<div id="mySidepanel" class="sidepanel">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
    <a href="{{ url_for('main.index') }}">Home</a>
    <a href="{{ url_for('main.about') }}">About</a>

    {% if not current_user.is_authenticated %}
    <a href="{{ url_for('auth.register') }}">Register</a>
    <a href="{{ url_for('auth.login') }}">Login</a>
    {% endif %}

    {% if current_user.is_authenticated %}
    <a href="{{ url_for('swimmer.profile') }}">Profile</a>
    <a href="{{ url_for('swimmer.swim') }}">Swim</a>
    {% endif %}

</div>
<!-- header -->
<header>
    <!-- header inner -->
    <div class="head-top">
        <div class="container-fluid">
            <div class="row d_flex">
                <div class="col-sm-3">
                    <div class="logo">
                        <a href="{{ url_for('main.index') }}"><img
                                src="{{ url_for('static',filename='img/logo.png') }}"/></a>
                    </div>
                </div>
                <div class="col-sm-9">
                    <ul class="email text_align_right">
                        {% if not current_user.is_authenticated %}
                            <li class="d_none">

                                <a href="{{ url_for('auth.login') }}">
                                    <i class="fa fa-user" aria-hidden="true"></i>
                                    Login
                                </a>
                            </li>
                        {% endif %}
                        {% if current_user.is_authenticated %}
                            <li class="d_none">
                                <a href="{{ url_for('swimmer.profile') }}">
                                        <i class="fa fa-user" aria-hidden="true"></i>
                                        {{ current_user.name }}
                                    </a>
                            </li>
                            <li>
                                <a href="{{ url_for('auth.logout') }}">
                                    <i class="fa fa-user" aria-hidden="true"></i>
                                    Logout
                                </a>
                            </li>
                        {% endif %}
                        <li>
                            <button class="openbtn" onclick="openNav()"><img
                                    src="{{ url_for('static',filename='img/menu_btn.png') }}"></button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- end header -->
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class=flashes>
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
{% block content %}
{% endblock %}
<!-- footer -->
<footer>
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <a class="logo_footer"><img src="{{ url_for('static',filename='img/logo.png') }}" alt="#"/></a>
                </div>
                <div class="col-md-5">
                    <div class="Informa conta">
                        <h3>Address</h3>
                        <ul>
                            <li>Department of Computer Science Kasetsart University <br>50 Phahon Yothin Road, Ladyao, Chatuchak,
                                Bangkok, Thailand 10900
                            </li>
                        </ul>
                    </div>

                </div>
                <div class="col-md-4">
                    <div class="Informa conta">
                        <h3>Contact Us</h3>
                        <ul>
                            <li><a href="Javascript:void(0)"> (+66) 2 562 5444
                            </a>
                            </li>
                            <li><a href="Javascript:void(0)"> <a href="https://cs.sci.ku.ac.th/"> cs.sci.ku.ac.th</a>
                            </a>
                            </li>
                        </ul>
                    </div>
                    <ul class="social_icon text_align_center">
                        <li><a href="Javascript:void(0)"><i class="fa fa-facebook-f"></i></a></li>
                        <li><a href="Javascript:void(0)"><i class="fa fa-X"></i></a></li>
                        <li><a href="Javascript:void(0)"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <div class="Informa">
                        <h3>Newsletter</h3>
                        <form class="newslatter_form">
                            <input class="ente" placeholder="Enter your email" type="text" name="Enter your email">
                            <button class="subs_btn">Subscribe</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright text_align_center">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 offset-md-1">
                        <p>© 2024 Swimming athlete registration system website created by students 
                            <br /> of the Computer Science Department, Kasetsart University.<br /></a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end footer -->
</body>

</html>

project/templates/login.html
{% extends "base.html" %}

{% block title %}Login | Swimming Detection{% endblock %}

{% block page_class %}inner_page{% endblock %}

{% block content %}
    <!-- BODY EMAIL PASSWORD -->
<div id="top_section" class=" banner_Login">
    <!--<div class="contact left_cross_right">-->
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                <!--<div class="titlepage text_align_left">
                        <h1>Login</h1>
                        <p>Please enter email address and password</p>
                    </div> -->
                </div>
                <section class="vh-100">
                    <div class="container-fluid h-custom">
                        <div class="row d-flex justify-content-center align-items-center h-100">
                            <div class="col-md-9 col-lg-6 col-xl-5">
                                <img src="{{ url_for('static',filename='img/right_side2.png') }}"
                                     class="img-fluid" alt="Sample image">
                            </div> 
                            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                                <form id="request" class="main_form" method="POST" action="/login">
                                    <!-- Email input -->
                                    <div class="form-outline mb-4">
                                        <label for="email">Email address</label>
                                        <input type="email" id="email" name="email" class="form-control form-control-lg"
                                               placeholder="Enter a valid email address"/>
                                        
                                    </div>

                                    <!-- Password input -->
                                    <div data-mdb-input-init class="form-outline mb-3">
                                        <label class="form-label" for="password">Password</label>
                                        <input type="password" id="password" name="password" class="form-control form-control-lg"
                                               placeholder="Enter password"/>
                                        
                                    </div>

                                    <div class="d-flex justify-content-between align-items-center">
                                        <!-- Checkbox -->
                                        <div class="form-check mb-0">
                                            <input class="form-check-input me-2" type="checkbox" value=""
                                                   id="remember" name="remember"/>
                                            <label class="form-check-label" for="remember">
                                                Remember me
                                            </label>
                                        </div>
                                        {#<a href="#!" class="text-body">Forgot password?</a>#}
                                    </div>

                                    <div class="text-center text-lg-start mt-4 pt-2">
                                        <button data-mdb-button-init data-mdb-ripple-init
                                                class="btn btn-primary btn-lg"
                                                style="padding-left: 2.5rem; padding-right: 2.5rem;">Login
                                        </button>
                                        <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a
                                                href="{{ url_for('auth.register') }}"
                                                class="link-danger">Register</a>
                                        </p>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <!-- end BODY EMAIL PASSWORD -->

    <!-- our_us -->
    <div class="our_mics">
        <div class="container">
            <div class="row">
                <div class="col-md-10 offset-md-1">
                    <div class="titlepage text_align_center">
                        <h2>About senior project</h2>
                        <p>Senior program analyzes swimming style and captures the number of strokes. Distance calculation Components of various systems of various circulatory systems According to the components of the vowel, which has complete information by recording frequency analysis statistics showing a graph of the sound. Help follow the development of important training programs to suit there.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-sm-6 margin_bottom40">
                    <div id="ho_show" class="mics">
                        <figure><img class="img_responsive" src="{{ url_for('static',filename='img/mics_img1.jpg') }}"
                                     alt="#"/></figure>
                        <div class="mics_icon">
                            <a href="javascript:void(0)">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 margin_bottom40">
                    <div id="ho_show" class="mics">
                        <figure><img class="img_responsive" src="{{ url_for('static',filename='img/mics_img2.jpg') }}"
                                     alt="#"/></figure>
                        <div class="mics_icon">
                            <a href="javascript:void(0)">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 margin_bottom40">
                    <div id="ho_show" class="mics">
                        <figure><img class="img_responsive" src="{{ url_for('static',filename='img/mics_img3.jpg') }}"
                                     alt="#"/></figure>
                        <div class="mics_icon">
                            <a href="javascript:void(0)">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 margin_bottom40">
                    <div id="ho_show" class="mics">
                        <figure><img class="img_responsive" src="{{ url_for('static',filename='img/mics_img4.jpg') }}"
                                     alt="#"/></figure>
                        <div class="mics_icon">
                            <a href="javascript:void(0)">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 margin_bottom40">
                    <div id="ho_show" class="mics">
                        <figure><img class="img_responsive" src="{{ url_for('static',filename='img/mics_img5.jpg') }}"
                                     alt="#"/></figure>
                        <div class="mics_icon">
                            <a href="javascript:void(0)">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 margin_bottom40">
                    <div id="ho_show" class="mics">
                        <figure><img class="img_responsive" src="{{ url_for('static',filename='img/mics_img6.jpg') }}"
                                     alt="#"/></figure>
                        <div class="mics_icon">
                            <a href="javascript:void(0)">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end our_mics -->
{% endblock %}

project/templates/profile.html
{% extends "base.html" %}

{% block title %}Profile | Swimming Detection{% endblock %}

{% block page_class %}inner_page{% endblock %}

{% block content %}
    <!-- Profile section -->
    <section style="background-color: #fff;">
        <div class="container py-5">

            <div class="row">
                <div class="col-lg-4">
                    <div class="card mb-4">
                        <div class="card-body text-center">
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp"
                                 alt="avatar"
                                 class="rounded-circle img-fluid" style="width: 150px;">
                            <h1 class="my-3 display-5 mb-4">{{ current_user.name }}</h1>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Full Name</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ current_user.name }}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Height</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ current_user.height }} cm</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Weight</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ current_user.weight }} kg</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Gender</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ current_user.gender }}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Age</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ current_user.calculate_age() }} years</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <table class="table table-striped">
                <thead class="thead-dark">
                <tr>
                    <th>Style</th>
                    <th>Time</th>
                    <th>Stroke</th>
                    <th>Strokes per Minute</th>
                    <th>Pool Length</th>
                    <th>Meter per Stroke</th>
                    <th>Date</th>
                </tr>
                </thead>
                <tbody>
                {% for record in current_user.swimming_records %}
                    <tr>
                        <td>{{ record.style }}</td>
                        <td>{{ record.time }}</td>
                        <td>{{ record.stroke }}</td>
                        <td>{{ record.strokes_per_minute }}</td>
                        <td>{{ record.pool_length }}</td>
                        <td>{{ record.calculate_meter_per_stroke() }}</td>
                        <td>{{ record.date.strftime("%d %b %Y %H:%M") }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        <p>Average Strokes per Minute of the Day: {{ average_strokes_per_minute }}</p>

        </div>
    </section>
     <!-- end Profile  section -->
{% endblock %}

project/templates/register.html
{% extends "base.html" %}

{% block title %}Register | Swimming Detection{% endblock %}

{% block page_class %}inner_page{% endblock %}

{% block content %}

    <section>
        
        <!--<div class="row d-flex justify-content-center align-items-center h-100"> -->
            <div class="col">
                <div class="card card-registration my-4">
                    <div class="row g-0">
                        <div class="col-xl-6 d-none d-xl-block">
                            <img src="{{ url_for('static',filename='img/left_side.png') }}"
                                 alt="Sample photo" class="img-fluid"
                                 style="border-top-left-radius: .25rem; border-bottom-left-radius: .25rem;"/>
                        </div>
                        <div class="col-xl-6">
                            <div class="card-body p-md-5 text-black">
                                <h1 class="mb-5 text-uppercase font-weight-bold">Register</h1>
                                <form id="request" method="POST" action="/register">
                                    {{ form.hidden_tag }} <!-- Include CSRF token -->

                                    <!-- Start Name -->
                                    <div data-mdb-input-init class="form-outline mb-4">
                                        {{ form.name.label }}
                                        {{ form.name(class="form-control form-control-lg") }}
                                    </div>
                                    <!-- End Name -->

                                    <!-- Start Email -->
                                    <div data-mdb-input-init class="form-outline mb-4">
                                        {{ form.email.label }}
                                       {% if form.email.errors %}
                                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                                            <div class="invalid-feedback">
                                                {% for error in form.email.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{ form.email(class="form-control form-control-lg") }}
                                        {% endif %}
                                    </div>
                                    <!-- End Email -->


                                    <div class="row">
                                        <div class="col-md-6 mb-4">
                                            <div data-mdb-input-init class="form-outline">
                                                {{ form.height.label }}
                                                {{ form.height(class="form-control form-control-lg") }}
                                            </div>
                                        </div>
                                        <div class="col-md-6 mb-4">
                                            <div data-mdb-input-init class="form-outline">
                                                {{ form.weight.label }}
                                                {{ form.weight(class="form-control form-control-lg") }}
                                            </div>
                                        </div>
                                    </div>

                                    <div class="d-md-flex justify-content-start align-items-center mb-4 py-2">

                                        {{ form.gender.label(class="mb-0 me-4 mr-3 font-weight-bold") }}

                                        {% for subfield in form.gender %}

                                            <div class="form-check form-check-inline mb-0 me-4">
                                                {{ subfield(class="form-check-input") }}
                                                {{ subfield.label(class="form-check-label") }}
                                            </div>

                                        {% endfor %}

                                    </div>

                                    <div data-mdb-input-init class="form-outline mb-4">
                                        {{ form.dob.label }}
                                        {% if form.dob.errors %}
                                            {{ form.dob(class="form-control form-control-lg is-invalid") }}
                                            <div class="invalid-feedback">
                                                {% for error in form.dob.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{ form.dob(class="form-control form-control-lg") }}
                                        {% endif %}
                                    </div>

                                    <!-- Start Password -->
                                    <div data-mdb-input-init class="form-outline mb-4">
                                        {{ form.password.label }}
                                        {% if form.password.errors %}
                                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                                            <div class="invalid-feedback">
                                                {% for error in form.password.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{ form.password(class="form-control form-control-lg") }}
                                        {% endif %}
                                    </div>

                                    <div data-mdb-input-init class="form-outline mb-4">
                                        {{ form.confirm.label }}
                                        {{ form.confirm(class="form-control form-control-lg") }}
                                    </div>

                                    <div class="d-flex justify-content-end pt-3">
                                        {{ form.submit(class="btn btn-warning btn-lg ms-2") }}
                                    </div>
                                     <!-- End Password -->
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}