project/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, Response, send_file
from werkzeug.security import generate_password_hash, check_password_hash
from project.forms import RegistrationForm
from project.models import db, User

from flask_login import login_required, login_user, logout_user
auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        # login code goes here
        email = request.form.get('email')
        password = request.form.get('password')
        remember = True if request.form.get('remember') else False

        user = User.query.filter_by(email=email).first()

        # check if the user actually exists
        # take the user-supplied password, hash it, and compare it to the hashed password in the database
        if not user:
            print("User not found")
            flash('The email address does not exist, please try again')
            return redirect(url_for('auth.login'))  # if the user doesn't exist or password is wrong, reload the page

        if not user or not check_password_hash(user.password, password):
            print("Invalid password")
            flash('Please check your password and try again.')
            return redirect(url_for('auth.login'))  # if the user doesn't exist or password is wrong, reload the page

        # if the above check passes, then we know the user has the right credentials
        login_user(user, remember=remember)
        return redirect(url_for('swimmer.profile'))

    return render_template('login.html')


@auth.route('/register', methods=["GET", "POST"])
def register():
    form = RegistrationForm(request.form)
    if request.method == "POST" and form.validate():
        print('validated')
        # code to validate and add user to database goes here
        email = form.email.data
        name = form.name.data
        password = form.password.data
        height = form.height.data
        weight = form.weight.data
        gender = form.gender.data
        dob = form.dob.data

        user = User.query.filter_by(
            email=email).first()  # if this returns a user, then the email already exists in database

        if user:  # if a user is found, we want to redirect back to signup page so user can try again
            flash('Email address already exists')
            return redirect(url_for('register'))

        # create a new user with the form data. Hash the password so the plaintext version isn't saved.
        new_user = User(email=email, name=name, password=generate_password_hash(password, method='pbkdf2:sha256'),
                        height=height, weight=weight, gender=gender, date_of_birth=dob)

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for('login'))

    return render_template('register.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

project/coach/__init__.py
from flask import Blueprint

coach = Blueprint('coach', __name__, url_prefix='/coach')

from project.coach import routes

project/coach/routes.py
from flask import render_template, session
from project.models import User, SwimmingRecord
from flask_login import login_required, login_user, logout_user
from project.coach import coach


@coach.route('/dashboard')
@login_required
def dashboard():
    swimmers = User.query.filter_by(role='swimmer').all()
    return render_template('coach/dashboard.html', swimmers=swimmers)


@coach.route('/swimmer/<swimmer_name>')
def swimmer_profile(swimmer_name):
    swimmer = User.query.filter_by(name=swimmer_name).first()
    # Filter records for a specific user within the date range
    swimming_records_today = SwimmingRecord.query.filter(
        SwimmingRecord.profile_id == swimmer.profile.id).all()
    print(swimming_records_today)

    # Calculate average strokes per minute
    total_strokes = sum(record.strokes_per_minute for record in swimming_records_today)
    average_strokes_per_minute = total_strokes / len(swimming_records_today) if swimming_records_today else 0

    return render_template('coach/swimmer_profile.html', swimmer=swimmer,
                           swimming_records=swimming_records_today,
                           average_strokes_per_minute=average_strokes_per_minute)

project/main.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/about')
def about():
    return render_template('about.html')

project/templates/coach/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">

    <!-- site metas -->
    <title>{% block title %}Coach Dashboard | Swimming Detection{% endblock %}</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- App icon -->
    <link rel="icon" href="https://upload.wikimedia.org/wikipedia/th/thumb/5/51/Logo_ku_th.svg/1200px-Logo_ku_th.svg.png">


    <!-- bootstrap css -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.css') }}">
    <!-- style css -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/style.css') }}">
    <!-- responsive-->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/responsive.css') }}">
    <!-- awesome font family -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />#}

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->

    <!-- Javascript files-->
    <script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/jquery-3.0.0.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/custom.js') }}"></script>

</head>
<!-- body -->
<body class="main-layout inner_page">
<!-- loader  -->
{#<div class="loader_bg">#}
{#    <div class="loader"><img src="{{ url_for('static',filename='img/loading.gif') }}" alt=""/></div>#}
{#</div>#}
<!-- end loader -->
<div id="mySidepanel" class="sidepanel">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
    <a href="{{ url_for('main.index') }}">Home</a>
    <a href="{{ url_for('main.about') }}">About</a>
</div>
<!-- header -->
<header>
    <!-- header inner -->
    <div class="head-top">
        <div class="container-fluid">
            <div class="row d_flex">
                <div class="col-sm-3">
                    <div class="logo">
                        <a href="{{ url_for('main.index') }}"><img
                                src="{{ url_for('static',filename='img/logo.png') }}"/></a>
                    </div>
                </div>
                <div class="col-sm-9">
                    <ul class="email text_align_right">
                        {% if not current_user.is_authenticated %}
                            <li class="d_none">

                                <a href="{{ url_for('auth.login') }}">
                                    <i class="fa fa-user" aria-hidden="true"></i>
                                    Login
                                </a>
                            </li>
                        {% endif %}
                        {% if current_user.is_authenticated %}
                            <li class="d_none">
                                <a href="{{ url_for('swimmer.profile') }}">
                                        <i class="fa fa-user" aria-hidden="true"></i>
                                        {{ current_user.name }}
                                    </a>
                            </li>
                            <li>
                                <a href="{{ url_for('auth.logout') }}">
                                    <i class="fa fa-user" aria-hidden="true"></i>
                                    Logout
                                </a>
                            </li>
                        {% endif %}
                        <li>
                            <button class="openbtn" onclick="openNav()"><img
                                    src="{{ url_for('static',filename='img/menu_btn.png') }}"></button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- end header -->
{% block content %}
{% endblock %}
<!-- footer -->
<footer>
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <a class="logo_footer"><img src="{{ url_for('static',filename='img/logo.png') }}" alt="#"/></a>
                </div>
                <div class="col-md-5">
                    <div class="Informa conta">
                        <h3>Address</h3>
                        <ul>
                            <li> ภาควิชาวิทยาการคอมพิวเตอร์ มหาวิทยาลัยเกษตรศาสตร์ <br>50 ถนนพหลโยธิน ลาดยาว จตุจักร,
                                กรุงเทพ, ประเทศไทย 10900
                            </li>
                        </ul>
                    </div>

                </div>
                <div class="col-md-4">
                    <div class="Informa conta">
                        <h3>Contact Us</h3>
                        <ul>
                            <li><a href="Javascript:void(0)"> (+66) 2 562 5444
                            </a>
                            </li>
                            <li><a href="Javascript:void(0)"> <a href="https://cs.sci.ku.ac.th/"> cs.sci.ku.ac.th</a>
                            </a>
                            </li>
                        </ul>
                    </div>
                    <ul class="social_icon text_align_center">
                        <li><a href="Javascript:void(0)"><i class="fa fa-facebook-f"></i></a></li>
                        <li><a href="Javascript:void(0)"><i class="fa fa-X"></i></a></li>
                        <li><a href="Javascript:void(0)"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <div class="Informa">
                        <h3>Newsletter</h3>
                        <form class="newslatter_form">
                            <input class="ente" placeholder="Enter your email" type="text" name="Enter your email">
                            <button class="subs_btn">Subscribe</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright text_align_center">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 offset-md-1">
                        <p>© 2024 เว็บไซต์ระบบลงทะเบียนนักกีฬาว่ายน้ำ จัดทำโดย <a href="https://cs.sci.ku.ac.th/">
                            นิสิตภาควิชาวิทยาการคอมพิวเตอร์ มก.</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end footer -->
</body>

</html>

project/templates/coach/dashboard.html
{% extends 'coach/base.html' %}

{% block content %}


    <div class="container bootdey p-4">
        <div class="row">
            <div class="col">
                <div class="user-widget-2">
                    <ul class="list-unstyled">
                        {% for swimmer in swimmers %}

                            <li class="media">
                                <img class="rounded-circle d-flex align-self-center"
                                     src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="">
                                <div class="media-body">
                                    <h5>{{ swimmer.name }}</h5>
                                    <p>Swimmer</p>
                                    <a class="read_more" href="{{ url_for('coach.swimmer_profile', swimmer_name=swimmer.name) }}">View Profile</a>
                                </div>
                                <i class="d-flex align-self-center fa fa-dot-circle-o color-success"></i></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

project/templates/coach/swimmer_profile.html
{% extends "base.html" %}

{% block title %}Profile | Swimming Detection{% endblock %}

{% block page_class %}inner_page{% endblock %}

{% block content %}
    <!-- Profile section -->
    <section style="background-color: #fff;">
        <div class="container py-5">

            <div class="row">
                <div class="col-lg-4">
                    <div class="card mb-4">
                        <div class="card-body text-center">
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp"
                                 alt="avatar"
                                 class="rounded-circle img-fluid" style="width: 150px;">
                            <h1 class="my-3 display-5 mb-4">{{ swimmer.name }}</h1>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Full Name</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ swimmer.name }}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Height</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ swimmer.profile.height }} cm</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Weight</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ swimmer.profile.weight }} kg</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Gender</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ swimmer.profile.gender }}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Age</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ swimmer.profile.calculate_age() }} years</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <table class="table table-striped">
                <thead class="thead-dark">
                <tr>
                    <th>Style</th>
                    <th>Time</th>
                    <th>Stroke</th>
                    <th>Strokes per Minute</th>
                    <th>Pool Length</th>
                    <th>Meter per Stroke</th>
                    <th>Date</th>
                </tr>
                </thead>
                <tbody>
                {% for record in swimmer.profile.swimming_records %}
                    <tr>
                        <td>{{ record.style }}</td>
                        <td>{{ record.time }}</td>
                        <td>{{ record.stroke }}</td>
                        <td>{{ record.strokes_per_minute }}</td>
                        <td>{{ record.pool_length }}</td>
                        <td>{{ record.calculate_meter_per_stroke() }}</td>
                        <td>{{ record.date.strftime("%d %b %Y %H:%M") }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        <p>Average Strokes per Minute of the Day: {{ average_strokes_per_minute }}</p>

        </div>
    </section>
     <!-- end Profile  section -->
{% endblock %}